---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-03-25T12:46:30Z"
  labels:
    app: stack-server-test-pod
  name: stack-server-test-pod
spec:
  containers:
    - image: harbor.lab.markaplay.net/dockerhub/redis/redis-stack-server:6.2.6-v6
      name: stack-server-test
      ports:
        - containerPort: 6379
          hostPort: 6379
      tty: true
      volumeMounts:
        - mountPath: /data
          name: redistack-persistant-pvc
  volumes:
    - name: redistack-persistant-pvc
      persistentVolumeClaim:
        claimName: redistack-persistant

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-03-25T12:46:30Z"
  labels:
    app: amp-api-management-test-pod
  name: amp-api-management-test-pod
spec:
  containers:
    - image: harbor.lab.markaplay.net/dockerhub/vincewth/amp-api-management:v1.0
      name: amp-api-management-test
      ports:
          - containerPort: 8080
            hostPort: 8080
      tty: true
      volume:
        - name: config
          configMap:
            name: amp-api-management-config



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amp-api-management-config
data:
  config.yaml: |
    port: 8081
    env: "Production"
    redis:
      address: "localhost:6379"
      db: 0
    amp:
      url: "https://my.amp.enpoint.com"
      username: "ReadUser"
      password: "5uper$eCretP4$$W0rd"
